.TH GCGRAPHT 1 gcgrapht
.SH NAME
gcgrapht - Generates a graph as a farbfeld file
.SH SYNOPSIS
gcgrapht [OPTIONS] ... [FUNCTION]
.SH DESCRIPTION
Generates a graph as a farbfeld file.
If there is not a function, it will read the standard input
.TP
.B -gs, --grid-size
Selects the size of the grid of the graph.
Example: -gs 16x16
.TP
.B -s, --size
Selects the size of the image in pixels.
Example: -s 1024x1024
.TP
.B -sg, --show-grid
If true, show grid marks, if false, it doesnt show it.
Example: -sg false
.TP
.B -lt, --line-thickness
Set the thickness of the graph's line in pixels.
Example: -lt 4
.TP
.B -gt, --grid-thickness
Set the thickness of the grid marks in pixels.
The thickness of the x and y axis will always be doubled the 
thickness of the grid.
Example: -gt 4
.TP
.B -bg, --background
Set the background color.
The color needs to be in hexadecimal.
Example: -bg 00FF00 (set the color to green)
-bg FF0000 (set the color to red)
.TP
.B -fg, --foreground
Set the foreground color (line color).
The color needs to be in hexadecimal.
Example: -fg FF0000 (set the color to red)
.TP
.B -gc, --grid-color
Set the grid color.
The color needs to be in hexadecimal.
Example: -fg FF0000 (set the color to red)
.TP
.B -ac, --axis-color
Set the xy axis color.
The color needs to be in hexadecimal.
Example: -fg FF0000 (set the color to red)
.TP
.B -o, --output
Set the output file.
If not set, the output file will be image.ff
.TP
.B -help
Display a help message 
.SH Examples
.TP
.B gcgrapht "math.cos(x)" -o cos.ff
Generates the graph of f(x)=cos(x)
.TP
.B echo -e "x^2\n2^x" | gcgrapht
Generates a graph with two functions, f(x) = x^2 and g(x) = 2^x
.SH AUTHOR
Written by Gabriel Martins
.SH COPYRIGHT
.P
Copyright (C) Gabriel Martins 2020. License GPLv3+: GNU GPL Version 3 or later. This is free software. You are free to change and redistribute it.   
There is NO WARRANTY, to the extent permited by law.   
.P
Copyright © 1994–2019 Lua.org, PUC-Rio.   
(This program uses the Lua C API to generate graphs)   
